INSERT INTO productos(nombre,precio,create_at) values ('Panasonic',800, NOW())
INSERT INTO productos(nombre,precio,create_at) values ('Sony',700, NOW())
INSERT INTO productos(nombre,precio,create_at) values ('Apple',1000, NOW())
INSERT INTO productos(nombre,precio,create_at) values ('Sony noteBook',200, NOW())
INSERT INTO productos(nombre,precio,create_at) values ('Hewlett Packard',200, NOW())
INSERT INTO productos(nombre,precio,create_at) values ('Bianchi',200, NOW())
INSERT INTO productos(nombre,precio,create_at) values ('Adidas',200, NOW())
INSERT INTO productos(nombre,precio,create_at) values ('Nike',100, NOW())
INSERT INTO productos(nombre,precio,create_at) values ('Reebok',200, NOW())